### PR TITLE
New Hotels and Transit page

### PR DESCRIPTION
**Pull request by andrewwoods**
I created some resources for out of town visitors to find nearby Hotels, and info about Transit.

### CODE REVIEW

**Comment by msurguy** [comment]
cc @jeremeamia let's merge and deploy this?

**Comment by simensen** [comment]
Merged. The auto deploy didn't trigger for some reason. Not sure why. Hard for me to debug since this is attached to @jeremeamia's personal account.

**Comment by jeremeamia** [comment]
Thanks Andrew and Beau. I could transfer ownership to pnwphp org, since the
speaker stuff  is public now.

## 

_Jeremy Lindblom (@jeremeamia https://twitter.com/jeremeamia)_
Software Engineer at Amazon Web Services http://aws.amazon.com/
Co-author of the AWS SDK for PHP http://aws.amazon.com/sdkforphp/ (
@awsforphp https://twitter.com/awsforphp)
President of the Seattle PHP User Group http://www.meetup.com/seaphp/ (
@seaphp https://twitter.com/seaphp)
Organizer of the Pacific Northwest PHP conference http://pnwphp.com/ (
pnwphp.com)
PHP-FIG http://www.php-fig.org/ Representative for the Guzzle
http://guzzlephp.org/ project

**Comment by simensen** [comment]
@jeremeamia We can talk about doing that sometime in the next bit. Would you feel comfortable giving me admin the organization so I can keep a better eye on it? If not then I think we can leave it here for now. Just make sure to ping me after a merge if it doesn't look like the changes are published within 5-10 minutes.

**Pull request merged**
