### PR TITLE
Revert "Develop"

### PR DESCRIPTION
**Pull request by simensen**
Reverts pnwphp/pnwphp.com#29

This is causing errors on the talks page. It claims that the model has no `reviewId` property; I don't have any real idea how the database/model stuff is setup here so I'm not sure why it would not be able to find this property but this is what is causing the error on the talks page.

### CODE REVIEW

**Comment by simensen** [comment]
I merged my own code but it is super late and I wanted to get this fixed and thought it would be the easiest way to do so. If it causes problems, my bad.

**Comment by postalservice14** [comment]
How is the site being "served"?  When I was running "artisan serve" I had to restart it after changing `database/pnwphp.php`.  Maybe we have to do that?

**Comment by simensen** [comment]
@postalservice14 I was using `artisan serve` locally and ran into the problems I described here. It wasn't running at all before I cloned the repo. When I cloned the repo I had these changes in it. I restarted `artisan serve` several times while trying to figure out what was going on.

On the live server, it is being served via nginx and I believe the server is restarted after deployment. Since I've seen the same problem locally with `artisan serve` I think that it is not a server-specific problem. It _might_ be a PHP version problem or something, though, but I'm not at all sure why that would matter here.

You're sure you have been able to see this code running locally and don't have any changes that were not committed that might be helping to make it work for you locally? Were there .env file settings that you have locally that might need to be added in our local environments (or the live servers environment) to get it to work? Thinking: anything that might have changed in your local install that might not show up on `git status` that might be contributing to things broken for us but not for you.

**Comment by postalservice14** [comment]
Well, that's just strange.  I removed `node_modules`, `.sass-cache`, and `vendor` and re-installed those, and now I get the error locally.

It was a missing `reviewId` element on one of the talks.

Thanks for your help

**Comment by simensen** [comment]
@postalservice14 Sure thing! Glad I could help.

**Pull request merged**
