### PR TITLE
Updates to sponsors and hotels

### PR DESCRIPTION
**Pull request by jeremeamia**
- Updated Cal's talk abstract
- Added and re-ranked some sponsors
- Added distance from venue to hotels
- Updated early bird date
- Added Google Analytics
- Fixed a typo

@simensen FYI: Merging some updates to master.

### CODE REVIEW

**Comment by jeremeamia** [comment]
@simensen It doesn't look like a deployment was triggered.

**Comment by simensen** [comment]
I don't know why this is not happening automatically. And since it is a private personal repo we can't really have me look at it too closely. If you want to ping me on merges to master I can try to manually publish as soon as I can. Otherwise, we could consider moving this repo to the org and then give me ownership of it so I can try and work out what is wrong with it and try to fix it.

It should be deployed now!

**Comment by jeremeamia** [comment]
Yeah, I'll probably move it this week sometime. Thanks!

**Comment by simensen** [comment]
Also, I see that you mentioned me earlier about the merge to master but I guess I lost that because I got email notification for a bunch of other merges too (to develop) and didn't think this one was different. :)

**Pull request merged**
